name: lemon_watch
description: Simplifies streams and observers
version: 1.0.9
homepage: https://github.com/Jerome-Saltmarsh/lemon_watch

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
