name: lemon_watch
description: Simplifies streams and observers
version: 1.1.4
homepage: https://github.com/Jerome-Saltmarsh/lemon_watch

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
